services:
  docs:
    image: my_polls_local_docs
    container_name: my_polls_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_polls:/app/my_polls:z
    ports:
      - '9000:9000'
    command: /start-docs
