# Generated by Django 5.1.11 on 2025-07-05 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
