# Generated by Django 5.1.11 on 2025-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_poll_pub_date_poll_created_at_poll_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
